/**
 * Parameter.csv 기준 `login_status`가 포함된 Event Code (v2.0.0 + 사용)
 * @see docs/ga-refactor/[GA Event] Parameter.csv
 */
export const EVENTS_WITH_LOGIN_STATUS = [
  'landing_btnCTA_click',
  'landing_page_view',
  'home_page_view',
  'topNavCreateImg_click',
  'topNavLogin_click',
  'topNavMypage_click',
  'home_tapExplore_click',
  'home_tapShop_click',
  'home_bannerBgImg_click',
  'home_spaceMore_click',
  'home_spaceCard_click',
  'home_spaceMoreCard_click',
  'home_styleMore_click',
  'home_styleCard_click',
  'home_page_scroll',
  'shop_page_view',
  'shop_search_submit',
  'shop_search_clear',
  'shop_filterSht_view',
  'shop_filterList_click',
  'shop_filterShtReset_click',
  'shop_listProduct_view',
  'shop_listEmpty_view',
  'shop_page_scroll',
  'topNavLogo_click',
  'shop_selectSheet_view',
  'shop_selectSheetItem_click',
  'shop_selectSheetAddItem_click',
  'shop_selectSheetRemove_click',
  'shop_selectSheetCTA_click',
  'shop_filterSht_submit',
  'loginSocial_page_view',
  'loginSocial_btnCTA_click',
  'loginSocial_toastLoginError_view',
  'signupForm_page_view',
  'signupForm_btnCTA',
  'signupComp_page_view',
  'selectMoodboard_page_view',
  'selectMoodboard_page_scroll',
  'selectFurniture_page_view',
  'selectFurniture_page_scroll',
  'selectFurniture_btnCTA_click',
  'selectMoodboard_card_click',
  'bannerDetail_page_view',
  'bannerDetail_btnCTA_click',
  'styleDetail_page_view',
  'styleList_cardStyle_click',
  'loadImg_page_view',
  'styleDetail_btnCTA_click',
  'roomType_listEmpty_view',
  'roomType_emptyListRecCard_view',
  'roomType_emptyListRecCard_click',
  'roomType_viewSht_submit',
  'home_webBanner_click',
] as const;

export type EventWithLoginStatus = (typeof EVENTS_WITH_LOGIN_STATUS)[number];

export const eventsWithLoginStatusSet = new Set<string>(
  EVENTS_WITH_LOGIN_STATUS
);
