// api 에러 코드
export const ERROR_CODES = {
  // 인증
  ACCESS_TOKEN_EXPIRED: 40002,
  // 이미지 생성
  IMAGE_QUOTA_EXCEEDED: 42900,
  IMAGE_LIMIT_EXCEEDED: 42901,
  IMAGE_ALREADY_REQUESTED: 40900,
  // HTTP
  HTTP_RATE_LIMITED: 429,
} as const;

/** 폴백 이미지 API로 전환해야 하는 에러 코드 */
export const FALLBACK_TRIGGER_CODES = new Set([
  ERROR_CODES.IMAGE_QUOTA_EXCEEDED,
  ERROR_CODES.IMAGE_LIMIT_EXCEEDED,
  ERROR_CODES.IMAGE_ALREADY_REQUESTED,
]);
