export const QUERY_KEY = {
  LANDING: 'landing',
  LOGIN: 'login',
  GENERATE_LOADING: 'generate-loading',
  GENERATE_RESULT: 'generate-result',
  GENERATE_FACTORS: 'generate-factors',
  GENERATE_FURNITURE_CATEGORIES: 'generate-furniture-categories',
  GENERATE_FURNITURE_CATEGORIES_GROUP: 'generate-furniture-categories-group',
  GENERATE_FURNITURE_PRODUCTS: 'generate-furniture-products',
  GENERATE_FURNITURE_PRODUCTS_GROUP: 'generate-furniture-products-group',
  GENERATE_FURNITURE_DASHBOARD: 'generate-furniture-dashboard',
  MYPAGE_USER: 'mypage-user',
  MYPAGE_IMAGES: 'mypage-images',
  MYPAGE_IMAGE_DETAIL: 'mypage-image-detail',
  USER: 'user',
  IMAGE_HISTORY: 'image-history',
  JJYM_LIST: 'jjym-list',
};
