export const PROGRESS_CONFIG = {
  SLOW_PHASE_END: 90,
  SLOW_INCREMENT: 0.1,
  SLOW_INTERVAL: 28,
  FAST_PHASE_END: 100,
  FAST_INCREMENT: 1,
  FAST_INTERVAL: 100,
  TOTAL_TIME: 27000,
  DELAY_BEFORE_COMPLETE_MS: 100,
} as const;
